name: Submodule updates
run-name: Github action to update submodule in another repo
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        env:
          EMAIL: ${{ secrets.EMAIL }}
          LOGIN: ${{ secrets.LOGIN }}
          NAME: ${{ secrets.NAME }}
          KEY: ${{ secrets.KEY }}
        steps:
            - name: Set Credentials
              run: git config --global user.email "$EMAIL" && git config --global user.name "$NAME"
            - name: Clone repo
              id: run_action
              run: git clone https://github.com/handbookhub/server.git
            - name: Update Credentials
              run: cd server && git remote set-url origin https://"$LOGIN":"$KEY"@github.com/handbookhub/server.git
            - name: Update repo, commit and push
              run: cd server && git submodule update --init --remote && git add . && git commit -m "update data submodule" && git push
