name: Submodule updates
run-name: Github action to update submodule in another repo
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        env:
          EMAIL: ${{ secrets.EMAIL }}
          NAME: ${{ secrets.NAME }}
        steps:
            - name: Set Credentials
              run: git config --global user.email "$EMAIL" && git config --global user.name "$NAME"
            - name: Clone repo
              id: run_action
              run: git clone https://github.com/handbookhub/handbookhub_server.git
            - name: Update repo
              run: cd handbookhub_server && git submodule update --remote
            - name: Commit and push
              run: cd handbookhub_server && git add . && git commit -m "update data submodule" && git push